// Run against the same isolated preview as check.mjs; no live daemon or ledger.
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { mkdtemp, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
const { chromium } = createRequire(import.meta.url)(process.env.PLAYWRIGHT_MODULE || 'playwright');
const out = await mkdtemp(join(tmpdir(), 'hakimi-research-workspace-'));
const browser = await chromium.launch({ headless: true, args: ['--disable-dev-shm-usage'] });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
const errors = [];
const apiRequests = [];
page.on('pageerror', error => errors.push(error.message));
page.on('request', request => { if (new URL(request.url()).pathname.startsWith('/api/')) apiRequests.push(request.url()); });
await page.route('**/*', route => route.request().url().startsWith('http://127.0.0.1:5193/')
  ? route.continue() : route.abort());
const call = (method, arg) => page.evaluate(([method, arg]) => window.researchPanelHarness[method](arg), [method, arg]);
const policy = page.getByRole('combobox', { name: 'Planning policy', exact: true });
const switcher = page.getByRole('button', { name: 'Research sessions', exact: true });
try {
  await page.goto('http://127.0.0.1:5193/', { waitUntil: 'networkidle' });
  await page.waitForFunction(() => !!window.researchPanelHarness);
  assert.equal(await call('sidebar'), true, 'Research collapses ordinary navigation');
  await call('toggleSidebar');
  assert.equal(await call('sidebar'), false, 'User can reopen navigation');
  for (const theme of ['light', 'dark']) {
    await call('theme', theme);
    await call('mode', 'inactive');
    await page.waitForFunction(() => !document.documentElement.hasAttribute('data-research-workspace'));
    assert.equal(await call('isDark'), theme === 'dark');
    const normal = await page.locator('.con').evaluate(el => getComputedStyle(el).backgroundColor);
    await call('mode', 'ready');
    await page.waitForFunction(() => window.researchPanelHarness.isDark());
    assert.equal(await page.locator('html').getAttribute('data-color-scheme'), theme, 'Saved theme is untouched');
    assert.equal(await page.locator('.con').evaluate(el => getComputedStyle(el).backgroundColor), 'rgb(10, 19, 34)');
    assert.equal(await page.locator('.research-star').count(), 48);
    await switcher.hover();
    await page.screenshot({ path: join(out, `observatory-${theme}.png`) });
    await switcher.focus();
    assert.equal(await switcher.evaluate(el => el.matches(':focus-visible')), true);
    await switcher.press('Enter');
    assert.equal(await page.getByRole('dialog').isVisible(), true);
    assert.equal(await page.getByRole('textbox', { name: 'Find a session, research line or workspace' }).evaluate(el => el === document.activeElement), true);
    await page.screenshot({ path: join(out, `sessions-${theme}.png`) });
    await page.keyboard.press('Escape');
    await call('mode', 'inactive');
    assert.equal(await page.locator('.con').evaluate(el => getComputedStyle(el).backgroundColor), normal, 'Normal theme restored exactly');
  }
  assert.equal(await call('sidebar'), false, 'Research did not overwrite normal sidebar preference');
  await call('toggleSidebar');
  await call('mode', 'ready');
  await call('toggleSidebar');
  await call('mode', 'inactive');
  assert.equal(await call('sidebar'), true, 'A previously collapsed normal sidebar remains collapsed');
  await call('mode', 'ready');
  await policy.selectOption('dreaming');
  await page.waitForFunction(() => !document.querySelector('.research-policy-select').disabled);
  assert.equal(await policy.inputValue(), 'dreaming');
  assert.equal(await page.locator('html').getAttribute('data-research-policy'), 'dreaming');
  await page.screenshot({ path: join(out, 'dreaming-observatory.png') });
  await call('reading');
  await page.locator('.katex').first().waitFor();
  await page.screenshot({ path: join(out, 'dreaming-reading.png') });
  await call('failPolicy', true);
  await policy.selectOption('collaborative');
  await page.waitForFunction(() => !document.querySelector('.research-policy-select').disabled);
  assert.equal(await policy.inputValue(), 'dreaming', 'Failed mode change resets to authoritative policy');
  assert.equal(await page.locator('html').getAttribute('data-research-policy'), 'dreaming', 'Failed policy change must not change the palette');
  await call('policyBusy', true);
  assert.equal(await policy.isDisabled(), true);
  await call('policyBusy', false);
  await switcher.click();
  await page.getByRole('textbox', { name: 'Find a session, research line or workspace' }).fill('/research/gw');
  assert.equal(await page.locator('.research-session-list').first().getByRole('button').count(), 1);
  await page.getByRole('button', { name: /Head-wing comparison/ }).click();
  assert.equal(await page.getByRole('dialog').count(), 0);
  assert.match(await page.locator('.research-workspace-name').innerText(), /Head-wing comparison/);
  assert.equal(await page.locator('html').getAttribute('data-research-policy'), null, 'Another session does not inherit Dreaming appearance');
  await page.getByRole('button', { name: 'Research board', exact: true }).click();
  assert.doesNotMatch(await page.locator('.research-compact').innerText(), /primitive evidence|Spin representation/);
  await page.screenshot({ path: join(out, 'switched-board.png') });
  await page.getByRole('button', { name: 'Hide research board', exact: true }).click();
  await switcher.click();
  await page.getByRole('button', { name: /Other loaded sessions/ }).click();
  assert.match(await page.getByRole('button', { name: /Unread candidate/ }).innerText(), /State unread/);
  await page.keyboard.press('Escape');
  await call('locale', 'zh');
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('button', { name: '研究会话', exact: true }).click();
  await page.screenshot({ path: join(out, 'mobile-sessions.png') });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth === innerWidth), true);
  await page.keyboard.press('Escape');
  await page.getByRole('button', { name: '研究看板', exact: true }).click();
  await page.screenshot({ path: join(out, 'mobile-board.png') });
  const commands = await page.evaluate(() => window.researchPanelHarness.commands);
  assert.deepEqual(commands.map(command => command.command?.kind ?? command.select), ['set_planning_policy', 'set_planning_policy', 'session-b']);
  assert.ok(commands.filter(command => command.command).every(command => command.id === 'session-a'));
  assert.deepEqual(apiRequests, [], 'Navigation list does not probe/resume sessions or mutate a real backend');
  assert.deepEqual(errors, []);
  await call('mode', 'inactive');
  assert.equal(await page.locator('html').getAttribute('data-research-policy'), null);
  assert.equal(await page.locator('.research-orbit-mark').count(), 0);
  await writeFile(join(out, 'report.json'), JSON.stringify({ passed: true, commands, apiRequests, errors }, null, 2));
  console.log(`Research workspace browser checks passed; screenshots: ${out}`);
} finally { await browser.close(); }
