export const ACTIVITY_PROGRESS_REVEAL_DELAY_MS = 8_000;
export const ACTIVITY_PROGRESS_FRAME_INTERVAL_MS = 250;
export const ACTIVITY_PROGRESS_MAX_PERCENT = 90;

export const ACTIVITY_PROGRESS_TIME_BASE_PERCENT = 8;
export const ACTIVITY_PROGRESS_TIME_RANGE_PERCENT = 52;
export const ACTIVITY_PROGRESS_TIME_CONSTANT_MS = 60_000;
export const ACTIVITY_PROGRESS_STEP_INCREMENT = 4;
export const ACTIVITY_PROGRESS_TOOL_CALL_INCREMENT = 3;
export const ACTIVITY_PROGRESS_TOOL_RESULT_INCREMENT = 4;

export const ACTIVITY_PROGRESS_BAR_MIN_WIDTH = 6;
export const ACTIVITY_PROGRESS_BAR_MAX_WIDTH = 16;
export const ACTIVITY_PROGRESS_BAR_FRAMES = ['▏', '▎', '▍', '▌', '▋', '▊', '▉'] as const;
