export { MCP_OAUTH_AUTHORIZATION_URL_TOOL_UPDATE } from '@moonshot-ai/protocol';

export type {
  AgentEvent,
  AgentStatusUpdatedEvent,
  AssistantDeltaEvent,
  BackgroundTaskStartedEvent,
  BackgroundTaskTerminatedEvent,
  CompactionBlockedEvent,
  CompactionCancelledEvent,
  CompactionCompletedEvent,
  CompactionResult,
  CompactionStartedEvent,
  CronFiredEvent,
  ErrorEvent,
  Event,
  GoalUpdatedEvent,
  HookResultEvent,
  McpOAuthAuthorizationUrlUpdateData,
  McpServerStatusEvent,
  McpServerStatusPayload,
  PluginCommandActivatedEvent,
  ResearchUpdatedEvent,
  AitpModeUpdatedEvent,
  SessionCreatedEvent,
  SessionMetaUpdatedEvent,
  SessionStatusChangedEvent,
  SessionWorkChangedEvent,
  SkillActivatedEvent,
  SubagentCompletedEvent,
  SubagentFailedEvent,
  SubagentSpawnedEvent,
  SubagentStartedEvent,
  SubagentSuspendedEvent,
  ThinkingDeltaEvent,
  ToolCallDeltaEvent,
  ToolCallStartedEvent,
  ToolInputDisplay,
  ToolListUpdatedEvent,
  ToolListUpdatedReason,
  ToolProgressEvent,
  ToolResultEvent,
  ToolUpdate,
  TurnEndedEvent,
  TurnEndReason,
  TurnStartedEvent,
  TurnStepCompletedEvent,
  TurnStepInterruptedEvent,
  TurnStepRetryingEvent,
  TurnStepStartedEvent,
  UsageStatus,
  WarningEvent,
} from '@moonshot-ai/protocol';

// AITP Research Mode — non-event wire types (snapshot, command, sub-shapes).
// Re-exported here so the node-sdk (which depends on agent-core, not on the
// protocol package directly) can import them through this barrel.
export type {
  ResearchStatusSnapshot,
  ResearchCommand,
  ResearchCommandRequest,
  ResearchCommandResponse,
  ResearchQuestion,
  ResearchLine,
  ResearchLineStatus,
  ResearchFocus,
  ResearchAlert,
  ResearchAlertKind,
  ResearchCommittedCursor,
  ResearchGoalSummary,
  AitpAdapterHealth,
  AitpModePhase,
  ResearchLoopStatus,
  QuestionWorkflow,
  QuestionEpistemic,
  QuestionPersistence,
} from '@moonshot-ai/protocol';

export type { KimiErrorPayload } from '../errors';
